// <auto-generated />
using System;
using JHT.Logistics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JHT.Logistics.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JhtDbContext))]
    [Migration("20260610053208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("ROL_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_MODIFICACION");

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ROL_DESCRIPCION");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_NOMBRE");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_MODIFICACION");

                    b.HasKey("RolId");

                    b.ToTable("TBL_CROL", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 32, 7, 740, DateTimeKind.Utc).AddTicks(2760),
                            RolDescripcion = "Control total del sistema",
                            RolNombre = "ADMINISTRADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 2,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 32, 7, 740, DateTimeKind.Utc).AddTicks(2766),
                            RolDescripcion = "Operación diaria",
                            RolNombre = "OPERADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 3,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 32, 7, 740, DateTimeKind.Utc).AddTicks(2768),
                            RolDescripcion = "Uso desde aplicación Flutter",
                            RolNombre = "CONDUCTOR",
                            UsuarioCreacion = "SYSTEM"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("USU_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_MODIFICACION");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("USU_EMAIL");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_LOGIN");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("USU_NOMBRE");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_PASSWORD_HASH");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_MODIFICACION");

                    b.HasKey("UsuId");

                    b.ToTable("TBL_UUSUARIO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.Property<int>("UsrId")
                        .HasColumnType("integer")
                        .HasColumnName("USR_ID");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    b.HasKey("UsrId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("TBL_RUSUARIO_ROL", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
