// <auto-generated />
using System;
using JHT.Logistics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JHT.Logistics.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JhtDbContext))]
    [Migration("20260610055736_AddConductorTable")]
    partial class AddConductorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CLI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CLI_DIRECCION");

                    b.Property<string>("CliEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CLI_EMAIL");

                    b.Property<string>("CliNombreComercial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_NOMBRE_COMERCIAL");

                    b.Property<string>("CliNumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_NUMERO_DOCUMENTO");

                    b.Property<string>("CliRazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_RAZON_SOCIAL");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_TELEFONO");

                    b.Property<string>("CliTipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CLI_TIPO_DOCUMENTO");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("CLI_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_FECHA_MODIFICACION");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_USUARIO_MODIFICACION");

                    b.HasKey("CliId");

                    b.HasIndex("CliNumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_TCLIENTE_NUMERO_DOCUMENTO");

                    b.ToTable("TBL_TCLIENTE", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Conductor", b =>
                {
                    b.Property<int>("ConId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CON_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConId"));

                    b.Property<string>("ConCodigoExterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_CODIGO_EXTERNO");

                    b.Property<string>("ConDni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CON_DNI");

                    b.Property<string>("ConEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CON_EMAIL");

                    b.Property<string>("ConNombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CON_NOMBRE_COMPLETO");

                    b.Property<string>("ConTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_TELEFONO");

                    b.Property<string>("ConTipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("CON_TIPO");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("CON_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CON_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CON_FECHA_MODIFICACION");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_USUARIO_MODIFICACION");

                    b.HasKey("ConId");

                    b.HasIndex("ConDni")
                        .IsUnique()
                        .HasDatabaseName("IX_TCONDUCTOR_DNI");

                    b.ToTable("TBL_TCONDUCTOR", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("ROL_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_MODIFICACION");

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ROL_DESCRIPCION");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_NOMBRE");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_MODIFICACION");

                    b.HasKey("RolId");

                    b.HasIndex("RolNombre")
                        .IsUnique()
                        .HasDatabaseName("IX_CROL_NOMBRE");

                    b.ToTable("TBL_CROL", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 57, 36, 162, DateTimeKind.Utc).AddTicks(3051),
                            RolDescripcion = "Control total del sistema",
                            RolNombre = "ADMINISTRADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 2,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 57, 36, 162, DateTimeKind.Utc).AddTicks(3056),
                            RolDescripcion = "Operación diaria",
                            RolNombre = "OPERADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 3,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 5, 57, 36, 162, DateTimeKind.Utc).AddTicks(3059),
                            RolDescripcion = "Uso desde aplicación Flutter",
                            RolNombre = "CONDUCTOR",
                            UsuarioCreacion = "SYSTEM"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("USU_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_MODIFICACION");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("USU_EMAIL");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_LOGIN");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("USU_NOMBRE");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_PASSWORD_HASH");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_MODIFICACION");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_UUSUARIO_EMAIL");

                    b.HasIndex("UsuLogin")
                        .IsUnique()
                        .HasDatabaseName("IX_UUSUARIO_LOGIN");

                    b.ToTable("TBL_UUSUARIO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.Property<int>("UsrId")
                        .HasColumnType("integer")
                        .HasColumnName("USR_ID");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    b.HasKey("UsrId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("TBL_RUSUARIO_ROL", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
