// <auto-generated />
using System;
using JHT.Logistics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JHT.Logistics.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JhtDbContext))]
    partial class JhtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AUD_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("AUD_ACCION");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUD_FECHA");

                    b.Property<string>("NombreTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AUD_TABLA");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AUD_REGISTRO_ID");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AUD_USUARIO");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("AUD_VALORES_ANTERIORES");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("AUD_VALORES_NUEVOS");

                    b.HasKey("Id");

                    b.HasIndex("NombreTabla")
                        .HasDatabaseName("IX_AAUDITORIA_TABLA");

                    b.HasIndex("RegistroId")
                        .HasDatabaseName("IX_AAUDITORIA_REGISTROID");

                    b.ToTable("TBL_AAUDITORIA", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.CEstadoServicio", b =>
                {
                    b.Property<int>("EstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EST_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstId"));

                    b.Property<string>("EstCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EST_CODIGO");

                    b.Property<string>("EstNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EST_NOMBRE");

                    b.HasKey("EstId");

                    b.HasIndex("EstCodigo")
                        .IsUnique()
                        .HasDatabaseName("IX_CESTADO_CODIGO");

                    b.ToTable("TBL_CESTADO_SERVICIO", (string)null);

                    b.HasData(
                        new
                        {
                            EstId = 1,
                            EstCodigo = "RECEPCIONADO",
                            EstNombre = "Recepcionado"
                        },
                        new
                        {
                            EstId = 2,
                            EstCodigo = "PROGRAMADO",
                            EstNombre = "Programado"
                        },
                        new
                        {
                            EstId = 3,
                            EstCodigo = "UNIDAD_ASIGNADA",
                            EstNombre = "Unidad Asignada"
                        },
                        new
                        {
                            EstId = 4,
                            EstCodigo = "EN_RUTA",
                            EstNombre = "En Ruta"
                        },
                        new
                        {
                            EstId = 5,
                            EstCodigo = "MUY_CERCA",
                            EstNombre = "Muy Cerca"
                        },
                        new
                        {
                            EstId = 6,
                            EstCodigo = "ENTREGADO",
                            EstNombre = "Entregado"
                        },
                        new
                        {
                            EstId = 7,
                            EstCodigo = "CANCELADO",
                            EstNombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.CTipoDocumento", b =>
                {
                    b.Property<int>("TipdocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TIPDOC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipdocId"));

                    b.Property<string>("TipdocCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TIPDOC_CODIGO");

                    b.Property<string>("TipdocNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TIPDOC_NOMBRE");

                    b.HasKey("TipdocId");

                    b.HasIndex("TipdocCodigo")
                        .IsUnique()
                        .HasDatabaseName("IX_CTIPDOC_CODIGO");

                    b.ToTable("TBL_CTIPO_DOCUMENTO", (string)null);

                    b.HasData(
                        new
                        {
                            TipdocId = 1,
                            TipdocCodigo = "GRE",
                            TipdocNombre = "Guía de Remisión"
                        },
                        new
                        {
                            TipdocId = 2,
                            TipdocCodigo = "FACTURA",
                            TipdocNombre = "Factura"
                        },
                        new
                        {
                            TipdocId = 3,
                            TipdocCodigo = "BOLETA",
                            TipdocNombre = "Boleta"
                        },
                        new
                        {
                            TipdocId = 4,
                            TipdocCodigo = "ORDEN_SERVICIO",
                            TipdocNombre = "Orden de Servicio"
                        },
                        new
                        {
                            TipdocId = 5,
                            TipdocCodigo = "ORDEN_COMPRA",
                            TipdocNombre = "Orden de Compra"
                        },
                        new
                        {
                            TipdocId = 6,
                            TipdocCodigo = "CARGO",
                            TipdocNombre = "Cargo de Entrega"
                        },
                        new
                        {
                            TipdocId = 7,
                            TipdocCodigo = "EVIDENCIA",
                            TipdocNombre = "Evidencia Fotográfica"
                        },
                        new
                        {
                            TipdocId = 8,
                            TipdocCodigo = "OTRO",
                            TipdocNombre = "Otro Documento"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CLI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CLI_DIRECCION");

                    b.Property<string>("CliEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CLI_EMAIL");

                    b.Property<string>("CliNombreComercial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_NOMBRE_COMERCIAL");

                    b.Property<string>("CliNumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_NUMERO_DOCUMENTO");

                    b.Property<string>("CliRazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_RAZON_SOCIAL");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_TELEFONO");

                    b.Property<string>("CliTipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CLI_TIPO_DOCUMENTO");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("CLI_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_FECHA_MODIFICACION");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLI_USUARIO_MODIFICACION");

                    b.HasKey("CliId");

                    b.HasIndex("CliNumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_TCLIENTE_NUMERO_DOCUMENTO");

                    b.ToTable("TBL_TCLIENTE", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Conductor", b =>
                {
                    b.Property<int>("ConId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CON_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConId"));

                    b.Property<string>("ConCodigoExterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_CODIGO_EXTERNO");

                    b.Property<string>("ConDni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CON_DNI");

                    b.Property<string>("ConEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CON_EMAIL");

                    b.Property<string>("ConNombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CON_NOMBRE_COMPLETO");

                    b.Property<string>("ConTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_TELEFONO");

                    b.Property<string>("ConTipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("CON_TIPO");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("CON_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CON_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CON_FECHA_MODIFICACION");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CON_USUARIO_MODIFICACION");

                    b.HasKey("ConId");

                    b.HasIndex("ConDni")
                        .IsUnique()
                        .HasDatabaseName("IX_TCONDUCTOR_DNI");

                    b.ToTable("TBL_TCONDUCTOR", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.DservicioDestino", b =>
                {
                    b.Property<int>("SerdesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SERDES_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerdesId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("SERDES_ESTADO_LOGICO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SERDES_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SERDES_FECHA_MODIFICACION");

                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<string>("SerdesContacto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("SERDES_CONTACTO");

                    b.Property<string>("SerdesDestinatario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("SERDES_DESTINATARIO");

                    b.Property<string>("SerdesDireccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SERDES_DIRECCION");

                    b.Property<string>("SerdesEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDES_ESTADO");

                    b.Property<string>("SerdesReferencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SERDES_REFERENCIA");

                    b.Property<string>("SerdesRuc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SERDES_RUC");

                    b.Property<int>("SerdesSecuencia")
                        .HasColumnType("integer")
                        .HasColumnName("SERDES_SECUENCIA");

                    b.Property<string>("SerdesTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDES_TELEFONO");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDES_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDES_USUARIO_MODIFICACION");

                    b.HasKey("SerdesId");

                    b.HasIndex("SerId");

                    b.ToTable("TBL_DSERVICIO_DESTINO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.DservicioDocumento", b =>
                {
                    b.Property<int>("SerdocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SERDOC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerdocId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("SERDOC_ESTADO_LOGICO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SERDOC_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SERDOC_FECHA_MODIFICACION");

                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<string>("SerdocArchivoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("SERDOC_ARCHIVO_URL");

                    b.Property<DateTime>("SerdocFechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SERDOC_FECHA_CARGA");

                    b.Property<string>("SerdocNombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("SERDOC_NOMBRE_ORIGINAL");

                    b.Property<string>("SerdocNumero")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SERDOC_NUMERO");

                    b.Property<int>("TipdocId")
                        .HasColumnType("integer")
                        .HasColumnName("TIPDOC_ID");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_CARGA");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDOC_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SERDOC_USUARIO_MODIFICACION");

                    b.HasKey("SerdocId");

                    b.HasIndex("SerId");

                    b.HasIndex("TipdocId");

                    b.ToTable("TBL_DSERVICIO_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.HservicioEstado", b =>
                {
                    b.Property<int>("HseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HSE_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HseId"));

                    b.Property<int>("EstId")
                        .HasColumnType("integer")
                        .HasColumnName("EST_ID");

                    b.Property<DateTime>("HseFechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HSE_FECHA_HORA");

                    b.Property<string>("HseObservacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("HSE_OBSERVACION");

                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_REGISTRO");

                    b.HasKey("HseId");

                    b.HasIndex("EstId");

                    b.HasIndex("SerId");

                    b.ToTable("TBL_HSERVICIO_ESTADO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.RservicioConductor", b =>
                {
                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<int>("ConId")
                        .HasColumnType("integer")
                        .HasColumnName("CON_ID");

                    b.Property<bool>("AsignacionActiva")
                        .HasColumnType("boolean")
                        .HasColumnName("ASIGNACION_ACTIVA");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_ASIGNACION");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_FIN");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<string>("MotivoCambio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MOTIVO_CAMBIO");

                    b.Property<string>("UsuarioAsignador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_ASIGNADOR");

                    b.HasKey("SerId", "ConId");

                    b.HasIndex("ConId");

                    b.ToTable("TBL_RSERVICIO_CONDUCTOR", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.RservicioVehiculo", b =>
                {
                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<int>("VehId")
                        .HasColumnType("integer")
                        .HasColumnName("VEH_ID");

                    b.Property<bool>("AsignacionActiva")
                        .HasColumnType("boolean")
                        .HasColumnName("ASIGNACION_ACTIVA");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_ASIGNACION");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_FIN");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<string>("MotivoCambio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MOTIVO_CAMBIO");

                    b.Property<string>("UsuarioAsignador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USUARIO_ASIGNADOR");

                    b.HasKey("SerId", "VehId");

                    b.HasIndex("VehId");

                    b.ToTable("TBL_RSERVICIO_VEHICULO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("ROL_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ROL_FECHA_MODIFICACION");

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ROL_DESCRIPCION");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_NOMBRE");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_USUARIO_MODIFICACION");

                    b.HasKey("RolId");

                    b.HasIndex("RolNombre")
                        .IsUnique()
                        .HasDatabaseName("IX_CROL_NOMBRE");

                    b.ToTable("TBL_CROL", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 7, 57, 35, 12, DateTimeKind.Utc).AddTicks(8181),
                            RolDescripcion = "Control total del sistema",
                            RolNombre = "ADMINISTRADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 2,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 7, 57, 35, 12, DateTimeKind.Utc).AddTicks(8186),
                            RolDescripcion = "Operación diaria",
                            RolNombre = "OPERADOR",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            RolId = 3,
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 10, 7, 57, 35, 12, DateTimeKind.Utc).AddTicks(8188),
                            RolDescripcion = "Uso desde aplicación Flutter",
                            RolNombre = "CONDUCTOR",
                            UsuarioCreacion = "SYSTEM"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("USU_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USU_FECHA_MODIFICACION");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("USU_EMAIL");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_LOGIN");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("USU_NOMBRE");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_PASSWORD_HASH");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USU_USUARIO_MODIFICACION");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_UUSUARIO_EMAIL");

                    b.HasIndex("UsuLogin")
                        .IsUnique()
                        .HasDatabaseName("IX_UUSUARIO_LOGIN");

                    b.ToTable("TBL_UUSUARIO", (string)null);

                    b.HasData(
                        new
                        {
                            UsuId = 1,
                            Estado = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsuEmail = "admin@jhtlogistics.com",
                            UsuLogin = "admin",
                            UsuNombre = "Administrador del Sistema",
                            UsuPasswordHash = "$2a$11$V.ZsAZaVSCnCTeiRY9u26OhFGxsL3/.ffZmNWC4VI5yjDo.X30dHa",
                            UsuarioCreacion = "SYSTEM"
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.Property<int>("UsrId")
                        .HasColumnType("integer")
                        .HasColumnName("USR_ID");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    b.HasKey("UsrId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("TBL_RUSUARIO_ROL", (string)null);

                    b.HasData(
                        new
                        {
                            UsrId = 1,
                            RolId = 1
                        });
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("SerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLI_ID");

                    b.Property<int>("EstId")
                        .HasColumnType("integer")
                        .HasColumnName("EST_ID");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("SER_ESTADO_LOGICO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SER_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SER_FECHA_MODIFICACION");

                    b.Property<string>("SerCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SER_CODIGO");

                    b.Property<string>("SerDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SER_DESCRIPCION");

                    b.Property<DateTime?>("SerFechaFinReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SER_FECHA_FIN_REAL");

                    b.Property<DateTime?>("SerFechaInicioReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SER_FECHA_INICIO_REAL");

                    b.Property<DateTime?>("SerFechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SER_FECHA_PROGRAMADA");

                    b.Property<string>("SerObservacion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("SER_OBSERVACION");

                    b.Property<string>("SerPrioridad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SER_PRIORIDAD");

                    b.Property<string>("SerTipoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SER_TIPO_SERVICIO");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SER_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SER_USUARIO_MODIFICACION");

                    b.HasKey("SerId");

                    b.HasIndex("CliId");

                    b.HasIndex("EstId");

                    b.HasIndex("SerCodigo")
                        .IsUnique()
                        .HasDatabaseName("IX_TSERVICIO_CODIGO");

                    b.ToTable("TBL_TSERVICIO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.TTrackingPublico", b =>
                {
                    b.Property<int>("TrkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TRK_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrkId"));

                    b.Property<int>("SerId")
                        .HasColumnType("integer")
                        .HasColumnName("SER_ID");

                    b.Property<bool>("TrkEstado")
                        .HasColumnType("boolean")
                        .HasColumnName("TRK_ESTADO");

                    b.Property<DateTime>("TrkFechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TRK_FECHA_CREACION");

                    b.Property<string>("TrkToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TRK_TOKEN");

                    b.HasKey("TrkId");

                    b.HasIndex("SerId")
                        .IsUnique()
                        .HasDatabaseName("IX_TTRACKING_SERVICIO");

                    b.HasIndex("TrkToken")
                        .IsUnique()
                        .HasDatabaseName("IX_TTRACKING_TOKEN");

                    b.ToTable("TBL_TTRACKING_PUBLICO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("VehId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VEH_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("VEH_ESTADO");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VEH_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VEH_FECHA_MODIFICACION");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VEH_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VEH_USUARIO_MODIFICACION");

                    b.Property<string>("VehCapacidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VEH_CAPACIDAD");

                    b.Property<string>("VehMarca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("VEH_MARCA");

                    b.Property<string>("VehModelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("VEH_MODELO");

                    b.Property<string>("VehPlaca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("VEH_PLACA");

                    b.Property<string>("VehTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VEH_TIPO");

                    b.HasKey("VehId");

                    b.HasIndex("VehPlaca")
                        .IsUnique()
                        .HasDatabaseName("IX_TVEHICULO_PLACA");

                    b.ToTable("TBL_TVEHICULO", (string)null);
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.DservicioDestino", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Destinos")
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.DservicioDocumento", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Documentos")
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.CTipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipdocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.HservicioEstado", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.CEstadoServicio", "EstadoServicio")
                        .WithMany()
                        .HasForeignKey("EstId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoServicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.RservicioConductor", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithMany("ConductoresAsignados")
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.RservicioVehiculo", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithMany("VehiculosAsignados")
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.UsuarioRol", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.Security.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JHT.Logistics.Domain.Entities.CEstadoServicio", "EstadoServicio")
                        .WithMany()
                        .HasForeignKey("EstId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoServicio");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.TTrackingPublico", b =>
                {
                    b.HasOne("JHT.Logistics.Domain.Entities.Servicio", "Servicio")
                        .WithOne("TrackingPublico")
                        .HasForeignKey("JHT.Logistics.Domain.Entities.TTrackingPublico", "SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Security.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("JHT.Logistics.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("ConductoresAsignados");

                    b.Navigation("Destinos");

                    b.Navigation("Documentos");

                    b.Navigation("HistorialEstados");

                    b.Navigation("TrackingPublico");

                    b.Navigation("VehiculosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
